# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI/CD - container to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_101a9056da7e4d0ba649f1cfbc497b4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_89298d835ce64422b5d5cbdbbc884a41 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_101a9056da7e4d0ba649f1cfbc497b4a }}/vihhcunha/thedevspace:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TheDevSpace'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8b9c69d8be6042b7922a98fc7210aa84 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_101a9056da7e4d0ba649f1cfbc497b4a }}/vihhcunha/thedevspace:${{ github.sha }}'