name: Trigger auto deployment for the-dev-space

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/the-dev-space-AutoDeployTrigger-9e52ed2c-e85e-4249-bc1c-34dbe08334d0.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_c2e0157d3aa147b680fe690b23616df3 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_65647285cdd74eb2897f8ba4eb83aa73 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c2e0157d3aa147b680fe690b23616df3 }}/thedevspace:${{ github.sha }}
          file: ./Dockerfile
          build-args: LICENSE_KEY=${{ secrets.LICENSE_KEY }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.THEDEVSPACE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n the-dev-space -g TestPurpose --server index.docker.io --username  ${{ secrets.THEDEVSPACE_REGISTRY_USERNAME }} --password ${{ secrets.THEDEVSPACE_REGISTRY_PASSWORD }}
            az containerapp update -n the-dev-space -g TestPurpose --image index.docker.io/vihhcunha/thedevspace:${{ github.sha }}
